CREATE TABLE [dbo].[ClientPosSettings]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[ClientIp] NVARCHAR(100) NOT NULL,
	[StoreId] NVARCHAR(100) NOT NULL,
	[TerminalId] NVARCHAR(100) NOT NULL,
 CONSTRAINT [PK_ClientPosSettings] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
