CREATE TABLE [dbo].[MonerisCallbackLog]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Response] NVARCHAR(Max) NOT NULL,
	[CreatedDate] DATETIME NOT NULL,
 CONSTRAINT [PK_MonerisCallbackLog] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
