CREATE TABLE [dbo].[Settings]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[AdminEmail] NVARCHAR(100) NOT NULL,
	[ReportEmail] NVARCHAR(100) NOT NULL,
	[FromEmail] NVARCHAR(100) NOT NULL,
	[FromEmailPassword] NVARCHAR(100) NOT NULL,
	[SmtpPort] INT NOT NULL,
	[SmtpHost] NVARCHAR(100) NOT NULL,
	[SmtpUseSsl] BIT NOT NULL,
	CONSTRAINT [PK_Settings] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
